### ISSUE TITLE
Default Program bug

### ISSUE THREAD

**Issue by Natendrtfm** [SuperFola/Ark#19]
**Ark-windows-x64.exe Bug**
After moving it to C:\Program Files (x86)\Ark\bin , i can't use it to launch the .ark file
that's kinda weird, because it worked before (when the file was on my Desktop)

**Comment by SuperFola** [comment]
How did it work? Did you use right clic then "open with"?

**Comment by Natendrtfm** [comment]
Yes i use "open with" , but now, even if the file is in Desktop , it don't work

**Comment by SuperFola** [comment]
Open with Ark I guess
But since you moved the executable you need to redo all the things (open with, select program, go to directory where Ark is now)
