### ISSUE TITLE
List all files and folders of the current directory or specified path

### ISSUE THREAD

**Issue by Natendrtfm** [SuperFola/Ark#28]
**Is your feature request related to a problem? Please describe.**
Well, i'm trying to do a sort of Command line OS (fo no reason), and i think it could be nice if i can list all files of the current Directory/Path

**Describe the solution you'd like**
Add a method to list all the files in a array

**Describe alternatives you've considered**
(listAllFiles ".") Files of the current directory (also default argument)
(listAllFiles "C:\\Users\\Natend\\Desktop\\Programmation") Mmh maybe not \\
**Additional context**
For creation of system that can see files (a.k.a : OS, IDE, Lots of things)

**Comment by SuperFola** [comment]
Should be implemented in a C++ module or in the FFI

**Comment by ahmedkrmn** [comment]
Can I work on this?

**Comment by SuperFola** [comment]
Yeah no problems!

**Comment by SuperFola** [comment]
Hi @ahmedkrmn, are you still on it?

**Comment by SuperFola** [comment]
fixed in 3df2f43 (wrong commit message, it references #58 instead of this issue)
