### ISSUE TITLE
Add REPL

### ISSUE THREAD

**Issue by SuperFola** [SuperFola/Ark#34]
Should be able to type in code, wait for `count("(") == count(")")` before compiling.
Store code in buffer, compile and execute after each line.

**Comment by rstefanic** [comment]
I'd like to take a shot at this, but where would you want the REPL code to be placed? `src/REPL`? I don't expect it to be anything too difficult, but if I had any questions, I'd report back here.

Once the REPL's been added, I could then add the repl flag to the command line options in main.

**Comment by SuperFola** [comment]
I think putting it under `include/Ark/REPL` and `src/REPL` would be good.

No problem, I'll be glad to answer your questions!
