### ISSUE TITLE
Import bugging

### ISSUE THREAD

**Issue by Natendrtfm** [SuperFola/Ark#37]
**Describe the bug**
i Tryed to run unittest.ark, and it says "ParseError: Couldn't find file Switch.ark" 
Note: i run it without the --lib argument
**To Reproduce**
1. Go to tests directory
2. Launch unittest.ark
3. See error

**Expected behavior**
I Expect to import the module, wich is already installed with Ark Releases

**Screenshots**
![image](https://user-images.githubusercontent.com/46384155/66269931-ba2b3e00-e84e-11e9-85a0-49e6d2ac4f2d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version : 3.0.5
**Additional context**
I think it's the import bugging because it happens on the first import

**Comment by SuperFola** [comment]
The first time you're compiling it, if the standard library isn't installed in the directory it's meant to be in, that's absolutely normal.

I'm trying to understand why it's failling (same error) when the compiled bytecode already exists

**Comment by SuperFola** [comment]
Okay, I found why, on windows `std::filesystem::last_write_time` is buggy, thus it returns a timestamp from the future, and the bytecode file appears to be older than the source code. Spotted in 588a81bc, can't do anything about it before Microsoft updates MSVC.
