### ISSUE TITLE
Can't build on MacOS with Travis

### ISSUE THREAD

**Issue by SuperFola** [SuperFola/Ark#45]

**Comment by hugoziviani** [comment]
Hello! can I help you in anything ? cheers.

**Comment by SuperFola** [comment]
Hey! If you know how to fix that issue I would love to get a PR, this has been annoying me for too long

**Comment by hugoziviani** [comment]
Ok. I'm gonna try.

**Comment by hugoziviani** [comment]
I found an Error in the compilation process. Could you check if is the same as you got?

1- First Error:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/variant:1455:48: error: no
      matching function for call to object of type 'std::__1::equal_to<void>'
    static_assert(std::is_convertible<decltype(_Operator{}(_VSTD::forward<_T1>(__t1), ...

**Comment by SuperFola** [comment]
Must be related to the version of clang used, which I can't change (well, I tried without success) :v

**Comment by hugoziviani** [comment]
Do you have any suggestion to get solved this error? I was trying and I got nothing yet.

**Comment by SuperFola** [comment]
Appart from setting up a temp repo with travis integration and updating the travis.yml to use the latest clang on macos and linux (2 tests are using it), not really 😥

I tried to find other travis.yml files for C++ with clang on macos, but the code they used didn't work for this project, and I don't really know why

**Comment by SuperFola** [comment]
Hi, any updates on this?

**Comment by hugoziviani** [comment]
I tried to compile with old versions pack, but I got nothing. Sorry... If you want, can assign to another person. Thanks and sorry.

**Comment by SuperFola** [comment]
No problem, this is a quite tricky issue! Hopefully some day we'll figure this out

**Comment by hugoziviani** [comment]
Thanks a lot for the patience.

**Comment by SuperFola** [comment]
Just discovered that we can fix this compilation problem, but we need to upgrade clang (and that's not very easy to do from my pov) AND we need MacOS 10.15 for filesystem support, but travis has only MacOS <= 10.14

Closing until it's updated on their side
