### ISSUE TITLE
toUpperCase and toLowerCase returning "Unknown error"

### ISSUE THREAD

**Issue by Natendrtfm** [SuperFola/Ark#52]
**Describe the bug**
toUpperCase and toLowerCase returning "Unknown Error"

**To Reproduce**
1.Import Case.ark
2. try (toLowerCase "Some StringYY sTuffY") or another string *NB : you can also do this with toUpperCase*
3. Enjoy the bug
*Note : sometimes it returns another error like bad allocation*
**Expected behavior**
Returning the string to lowercase (or to upper)

**Screenshots**
![image](https://user-images.githubusercontent.com/46384155/67287404-615cd600-f4db-11e9-8b88-7e16e75369ec.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bits
 - Version 3.0.7

**Additional context**
Seems to happen with the latest version of Case.ark (i tried with an old version and it works)

**Comment by SuperFola** [comment]
By the look of your import instruction I think you're using an old version of the standard library, because since the 3.0.7, the lib has changed (in term of code *and* organization). Could you try to download the latest version of the standard library, and see if the bug is still present?

**Comment by Natendrtfm** [comment]
Yup
That was the old std lib files that i was using
