### ISSUE TITLE
EOF in REPL 

### ISSUE THREAD

**Issue by FrenchMasterSword** [SuperFola/Ark#66]
**Describe the bug**
When sending End of File to the REPL, it prints indefinitely the prompt `>> `

**To Reproduce**
1. `Ark -r`
2. <kbd>Ctrl</kbd> + <kbd>D</kbd> (`^D`)
3. `>> ` is printed indefinitely

**Expected behavior**
The REPL exits

**Desktop (please complete the following information):**
OS: Arch Linux
Ark compiled with `g++ (GCC) 9.2.0` from branch `dev`

**Comment by SuperFola** [comment]
Found out we have the same bug on WSL, g++8, but not on Windows with MSVC. Must be because we should have a `std::cin.ignore()` to avoid this and clear std::cin buffer, what do you think @rstefanic ?

**Comment by rstefanic** [comment]
I don't think the cin buffer would need to be cleared.

If I recall, `std::getline(...)` actually returns a stream. So it may just be best to check the stream returned using a while loop instead of a for loop. I can look into this tonight.
